### ISSUE TITLE
rancher.docker.engine should be an allowed property

### ISSUE THREAD

**Issue by matthewhartstonge** [joshwget/validator#2]
Unless the spec has changed, specifying a docker version under cloud-init should be valid given a `rancher.docker.engine` yaml mapping.

See: https://docs.rancher.com/os/configuration/switching-docker-versions/

For Example:

```yaml
#cloud-config
rancher:
  docker:
    engine: docker-1.12.6
```
